SELECT * FROM TEST_MEMBER ;

INSERT INTO TEST_MEMBER VALUES (10, 'rao', sysdate);
SELECT * FROM TEST_MEMBER ;

INSERT INTO TEST_MEMBER VALUES (22, 'kelvin','1994-07-12');
INSERT INTO TEST_MEMBER VALUES (27, 'IM','2020-04-07');
INSERT INTO TEST_MEMBER VALUES ('', 'sangbin','');

SELECT * FROM TEST_MEMBER ;


